### PR TITLE
[iOS] Fix "react_native_menu-Swift.h" cannot be found

### PR DESCRIPTION
**Pull request by alantoa**
# Overview
CleanShot 2024-05-12 at 03 32 21@2x
I noticed that many users have been [facing this build error ](https://github.com/react-native-menu/menu/issues/801)on iOS since the last version was released. It is due to a change made in this [PR](https://github.com/react-native-menu/menu/pull/803).

I assume that this import is correct, but I'm not sure why @svbutko still encountered this issue. Could you please check if the build error is related to this? Thank you!

# Test Plan

After changing it to `#import <react_native_menu/react_native_menu-Swift.h>`, the error disappeared.CleanShot 2024-05-12 at 03 38 08@2x

### CODE REVIEW

**Comment by svbutko** [comment]
Hey, @alantoa, the issue to which you are referring was happening before my PR the issue happens in NEW ARCH, while my fix fixes it for OLD ARCH

**Comment by Darren120** [comment]
> Hey, @alantoa, the issue to which you are referring was happening before my PR the issue happens in NEW ARCH, while my fix fixes it for OLD ARCH.
> 
> You can check the version to which people are referring is 1.0.2 and what they are using
> 
> And that it happened more than 2 days before my PR was merged and released
> 
> Are you sure that you are using OLD ARCH?

is it possible for expo to auto upgrade this package when doing npx expo upgrade --fix?

**Comment by Albert-Gao** [comment]
> Yeah, that's kind of weird. Ideally, it should work for both versions, but only v1.0.2 works for me. Let me take another look then.

Wow, thanks, downgrade to v1.0.2 + Old Arch works now! Thanks! :)

"expo": "~51.0.8",
"react-native": "0.74.1",
"@react-native-menu/menu": "1.0.2",

**Comment by tompetk** [comment]
Any updates on this?

**Comment by awilson9** [comment]
+1 this is actively broken

**Comment by SohelIslamImran** [comment]
image
Having same issue

**Comment by fobos531** [comment]
Hey @Naturalclar - do you have the bandwidth to take a look at this?

**Review by Naturalclar — APPROVED** [review]
LGTM

**Comment by thunderfalco** [comment]
image
still have this error

**Comment by mrousavy** [comment]
Hey! Thanks for this PR, but unfortunately for me it was the other way around - this PR broke the build now, while the previous release worked fine.

I think we should revert this, the previous way is the correct way of doing things (at least on latest Xcode).

Or maybe add an additional `#if __has_include` check to try both ways?

**Comment by mrousavy** [comment]
Created a fix for this here: https://github.com/react-native-menu/menu/pull/832 cc @Naturalclar

**Comment by alantoa** [comment]
Thanks, Marc! 
Yeah, adding the `#if __has_include` condition should work for both cases!

**Comment by mrousavy** [comment]
I'm curious why that works though. Why is it sometimes in a directory, and sometimes not?

**Comment by dancixx** [comment]
This error still comes up on new arch. @alantoa

**Comment by alantoa** [comment]
hey @dancixx what if you were to use this patch?
https://github.com/react-native-menu/menu/pull/832

**Pull request merged**
